Update api definition
natxomutxatxo/apiPersons pull request #1
Opened 2017-10-17 21:20 UTC by shavic

Defiinición del api personas

2017-10-17 23:28 UTC, natxomutxatxo requested changes

2017-10-17 23:28 UTC, natxomutxatxo commented on api.yaml
> +  /people/{personId}:
vamos a llamarlo /persons

2017-10-17 23:28 UTC, natxomutxatxo commented on api.yaml
> +basePath: "/v1"
pongamosle un nombre descriptivo, por ejemplo: persons

2017-10-17 23:28 UTC, natxomutxatxo commented on api.yaml
> +  /people/:
persons, y ponganos los recursos ordenados, primero /persons y despues /persons/{personId}

2017-10-17 23:28 UTC, natxomutxatxo commented on api.yaml
> +        200:
añade algun código de error ... 404, 500 , etc

2017-10-17 23:28 UTC, natxomutxatxo commented on api.yaml
> +  Person:
Añade algunos campos de contacto, minimo el numero de telefono

2017-10-18 17:00 UTC, shavic commented
Se atenderán las observaciones, gracias.

2017-10-18 17:00 UTC, closed without merging